[project]
name = "joel-expts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dill>=0.3.9",
    "numpy>=2.2.3",
    "rust-just>=1.40.0",
]
