[project]
name = "joel-expts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dill>=0.3.9",
    "mpi4py>=4.0.3",
    "numpy>=1,<2",
    "rust-just>=1.40.0",
]

[dependency-groups]
dev = ["mypy>=1.15.0", "ruff>=0.11.0"]


[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
